version: '3.8'

services:
  nextjs:
    image: ${DOCKER_REGISTRY:-docker.io}/${DOCKER_USERNAME}/nextjs-dockerise:${TAG:-latest}
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s
    networks:
      - nextjs-network

networks:
  nextjs-network:
    driver: bridge 